// This class is autogenerated. Do not modify.

using Microsoft.Maui.Controls;

namespace Telerik.Theming.Platform.Swatches;

public partial class Dark : ResourceDictionary
{
    public Dark()
    {
#if ANDROID
        this.Add("RadPrimaryColor", Microsoft.Maui.Graphics.Color.FromArgb("#BB86FC"));
#elif IOS || MACCATALYST
        this.Add("RadPrimaryColor", Microsoft.Maui.Graphics.Color.FromArgb("#0A84FF"));
#elif WINDOWS
        var color = (global::Windows.UI.Color)Microsoft.UI.Xaml.Application.Current.Resources["SystemAccentColorLight2"] ;
        this.Add("RadPrimaryColor", Microsoft.Maui.Graphics.Color.FromRgba(color.R, color.G, color.B, color.A));
#endif

        InitializeComponent();
    }
}