// This class is autogenerated. Do not modify.

using Microsoft.Maui.Controls;

namespace Telerik.Theming.Platform.Swatches;

public partial class Light : ResourceDictionary
{
    public Light()
    {
#if ANDROID
        this.Add("RadPrimaryColor", Microsoft.Maui.Graphics.Color.FromArgb("#2B0B98"));
#elif IOS || MACCATALYST
        this.Add("RadPrimaryColor", Microsoft.Maui.Graphics.Color.FromArgb("#007AFF"));
#elif WINDOWS
        var color = (global::Windows.UI.Color)Microsoft.UI.Xaml.Application.Current.Resources["SystemAccentColorDark1"];
        this.Add("RadPrimaryColor", Microsoft.Maui.Graphics.Color.FromRgba(color.R, color.G, color.B, color.A));
#endif

        InitializeComponent();
    }
}