// This class is autogenerated. Do not modify.

using Microsoft.Maui.Controls;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;

namespace WatchStore.Maui;

public partial class TelerikThemeResources : ResourceDictionary
{
    private static readonly Lazy<ResourceDictionary> Platform_Swatch_Light = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Swatches.Light());
    private static readonly Lazy<ResourceDictionary> Platform_Swatch_Dark = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Swatches.Dark());
    private static readonly Lazy<ResourceDictionary> Platform_Variables = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Variables());
    private static readonly Lazy<ResourceDictionary> Platform_AIPrompt_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.AIPrompt());
    private static readonly Lazy<ResourceDictionary> Platform_Accordion_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Accordion());
    private static readonly Lazy<ResourceDictionary> Platform_AutoComplete_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.AutoComplete());
    private static readonly Lazy<ResourceDictionary> Platform_BadgeView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.BadgeView());
    private static readonly Lazy<ResourceDictionary> Platform_BottomSheet_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.BottomSheet());
    private static readonly Lazy<ResourceDictionary> Platform_BusyIndicator_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.BusyIndicator());
    private static readonly Lazy<ResourceDictionary> Platform_Buttons_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Buttons());
    private static readonly Lazy<ResourceDictionary> Platform_Calendar_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Calendar());
    private static readonly Lazy<ResourceDictionary> Platform_Chat_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Chat(Platform_Entry_Styles.Value, Platform_Toolbar_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Platform_CheckBox_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.CheckBox());
    private static readonly Lazy<ResourceDictionary> Platform_CollectionView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.CollectionView());
    private static readonly Lazy<ResourceDictionary> Platform_ComboBox_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.ComboBox());
    private static readonly Lazy<ResourceDictionary> Platform_DataGrid_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.DataGrid());
    private static readonly Lazy<ResourceDictionary> Platform_DataForm_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.DataForm());
    private static readonly Lazy<ResourceDictionary> Platform_DataPager_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.DataPager());
    private static readonly Lazy<ResourceDictionary> Platform_Entry_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Entry());
    private static readonly Lazy<ResourceDictionary> Platform_Expander_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Expander());
    private static readonly Lazy<ResourceDictionary> Platform_GridSplitter_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.GridSplitter());
    private static readonly Lazy<ResourceDictionary> Platform_ImageEditor_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.ImageEditor(Platform_Buttons_Styles.Value, Platform_Toolbar_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Platform_LinearProgressBar_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.LinearProgressBar());
    private static readonly Lazy<ResourceDictionary> Platform_MaskedEntry_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.MaskedEntry(Platform_Entry_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Platform_NavigationView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.NavigationView());
    private static readonly Lazy<ResourceDictionary> Platform_NumericInput_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.NumericInput());
    private static readonly Lazy<ResourceDictionary> Platform_PdfViewer_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.PdfViewer(Platform_Entry_Styles.Value, Platform_Toolbar_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Platform_Pickers_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Pickers());
    private static readonly Lazy<ResourceDictionary> Platform_PromptInput_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.PromptInput(Platform_Entry_Styles.Value, Platform_Toolbar_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Platform_Rating_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Rating());
    private static readonly Lazy<ResourceDictionary> Platform_RichTextEditor_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.RichTextEditor(Platform_Buttons_Styles.Value, Platform_Toolbar_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Platform_Scheduler_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Scheduler());
    private static readonly Lazy<ResourceDictionary> Platform_SegmentedControl_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.SegmentedControl());
    private static readonly Lazy<ResourceDictionary> Platform_SignaturePad_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.SignaturePad());
    private static readonly Lazy<ResourceDictionary> Platform_Skeleton_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Skeleton());
    private static readonly Lazy<ResourceDictionary> Platform_Sliders_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Sliders());
    private static readonly Lazy<ResourceDictionary> Platform_SlideView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.SlideView());
    private static readonly Lazy<ResourceDictionary> Platform_SpeechToTextButton_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.SpeechToTextButton());
    private static readonly Lazy<ResourceDictionary> Platform_TabView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.TabView());
    private static readonly Lazy<ResourceDictionary> Platform_Toolbar_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.Toolbar(Platform_Entry_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Platform_TreeDataGrid_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.TreeDataGrid(Platform_DataGrid_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Platform_TreeView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Platform.Styles.TreeView());
    private static readonly Lazy<ResourceDictionary> Telerik_Swatch_Main = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Swatches.Main());
    private static readonly Lazy<ResourceDictionary> Telerik_Swatch_MainDark = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Swatches.MainDark());
    private static readonly Lazy<ResourceDictionary> Telerik_Swatch_OceanBlue = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Swatches.OceanBlue());
    private static readonly Lazy<ResourceDictionary> Telerik_Swatch_OceanBlueDark = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Swatches.OceanBlueDark());
    private static readonly Lazy<ResourceDictionary> Telerik_Swatch_Purple = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Swatches.Purple());
    private static readonly Lazy<ResourceDictionary> Telerik_Swatch_PurpleDark = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Swatches.PurpleDark());
    private static readonly Lazy<ResourceDictionary> Telerik_Swatch_Turquoise = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Swatches.Turquoise());
    private static readonly Lazy<ResourceDictionary> Telerik_Swatch_TurquoiseDark = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Swatches.TurquoiseDark());
    private static readonly Lazy<ResourceDictionary> Telerik_Variables = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Variables());
    private static readonly Lazy<ResourceDictionary> Telerik_AIPrompt_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.AIPrompt(Telerik_Buttons_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_Accordion_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Accordion());
    private static readonly Lazy<ResourceDictionary> Telerik_AutoComplete_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.AutoComplete());
    private static readonly Lazy<ResourceDictionary> Telerik_BadgeView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.BadgeView());
    private static readonly Lazy<ResourceDictionary> Telerik_BottomSheet_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.BottomSheet());
    private static readonly Lazy<ResourceDictionary> Telerik_BusyIndicator_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.BusyIndicator());
    private static readonly Lazy<ResourceDictionary> Telerik_Buttons_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Buttons());
    private static readonly Lazy<ResourceDictionary> Telerik_Calendar_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Calendar());
    private static readonly Lazy<ResourceDictionary> Telerik_Chat_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Chat(Telerik_Buttons_Styles.Value, Telerik_Entry_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_Chart_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Chart());
    private static readonly Lazy<ResourceDictionary> Telerik_CheckBox_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.CheckBox());
    private static readonly Lazy<ResourceDictionary> Telerik_CollectionView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.CollectionView());
    private static readonly Lazy<ResourceDictionary> Telerik_ComboBox_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.ComboBox(Telerik_Buttons_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_DataGrid_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.DataGrid(Telerik_Buttons_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_DataForm_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.DataForm());
    private static readonly Lazy<ResourceDictionary> Telerik_DataPager_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.DataPager());
    private static readonly Lazy<ResourceDictionary> Telerik_Entry_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Entry());
    private static readonly Lazy<ResourceDictionary> Telerik_Expander_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Expander());
    private static readonly Lazy<ResourceDictionary> Telerik_GridSplitter_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.GridSplitter());
    private static readonly Lazy<ResourceDictionary> Telerik_ImageEditor_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.ImageEditor(Telerik_Buttons_Styles.Value, Telerik_Toolbar_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_LinearProgressBar_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.LinearProgressBar());
    private static readonly Lazy<ResourceDictionary> Telerik_NavigationView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.NavigationView());
    private static readonly Lazy<ResourceDictionary> Telerik_NumericInput_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.NumericInput(Telerik_Buttons_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_PdfViewer_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.PdfViewer(Telerik_BusyIndicator_Styles.Value, Telerik_Entry_Styles.Value, Telerik_Toolbar_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_Pickers_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Pickers(Telerik_Buttons_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_PromptInput_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.PromptInput(Telerik_Buttons_Styles.Value, Telerik_Entry_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_Rating_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Rating());
    private static readonly Lazy<ResourceDictionary> Telerik_RichTextEditor_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.RichTextEditor(Telerik_Buttons_Styles.Value, Telerik_Toolbar_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_Scheduler_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Scheduler(Telerik_Buttons_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_SegmentedControl_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.SegmentedControl());
    private static readonly Lazy<ResourceDictionary> Telerik_SignaturePad_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.SignaturePad());
    private static readonly Lazy<ResourceDictionary> Telerik_Skeleton_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Skeleton());
    private static readonly Lazy<ResourceDictionary> Telerik_Sliders_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Sliders());
    private static readonly Lazy<ResourceDictionary> Telerik_SlideView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.SlideView());
    private static readonly Lazy<ResourceDictionary> Telerik_SpeechToTextButton_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.SpeechToTextButton());
    private static readonly Lazy<ResourceDictionary> Telerik_TabView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.TabView());
    private static readonly Lazy<ResourceDictionary> Telerik_Toolbar_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.Toolbar());
    private static readonly Lazy<ResourceDictionary> Telerik_TreeDataGrid_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.TreeDataGrid(Telerik_DataGrid_Styles.Value));
    private static readonly Lazy<ResourceDictionary> Telerik_TreeView_Styles = new Lazy<ResourceDictionary>(() => new Telerik.Theming.Telerik.Styles.TreeView(Telerik_CheckBox_Styles.Value));

    private TelerikTheme theme = TelerikTheme.Default;

    public TelerikThemeResources()
    {
        InitializeComponent();

        this.MergeThemeResources();
    }

    public static TelerikThemeResources? Current
    {
        get
        {
            return Application.Current?.Resources.MergedDictionaries.OfType<TelerikThemeResources>().FirstOrDefault();
        }
    }

    public static TelerikTheme AppTheme
    {
        get
        {
            return Current.Theme;
        }
        set
        {
            Current.Theme = value;
        }
    }

    public TelerikTheme Theme
    {
        get
        {
            return this.theme;
        }

        set
        {
            if (this.theme == value)
            {
                return;
            }

            this.theme = value;

            // Clear the last theme.
            this.MergedDictionaries.Clear();
            this.MergeThemeResources();
        }
    }

    /// <summary>
    /// Synchronously load and parse all XAML files related to theming.
    /// This may take a few seconds, but after it, runtime theme switch will be fast.
    /// </summary>
    public static async Task PrefetchAsync(Action<int, int> progress)
    {
        var tasks = new List<Lazy<ResourceDictionary>>()
        {
            Platform_Swatch_Light,
            Platform_Swatch_Dark,
            Telerik_Swatch_Main,
            Telerik_Swatch_MainDark,
            Telerik_Swatch_OceanBlue,
            Telerik_Swatch_OceanBlueDark,
            Telerik_Swatch_Purple,
            Telerik_Swatch_PurpleDark,
            Telerik_Swatch_Turquoise,
            Telerik_Swatch_TurquoiseDark,
            Platform_Variables,
            Telerik_Variables,
            Platform_AIPrompt_Styles,
            Platform_Accordion_Styles,
            Platform_AutoComplete_Styles,
            Platform_BadgeView_Styles,
            Platform_BottomSheet_Styles,
            Platform_BusyIndicator_Styles,
            Platform_Buttons_Styles,
            Platform_Calendar_Styles,
            Platform_Chat_Styles,
            Platform_CheckBox_Styles,
            Platform_CollectionView_Styles,
            Platform_ComboBox_Styles,
            Platform_DataGrid_Styles,
            Platform_DataForm_Styles,
            Platform_DataPager_Styles,
            Platform_Entry_Styles,
            Platform_Expander_Styles,
            Platform_GridSplitter_Styles,
            Platform_ImageEditor_Styles,
            Platform_LinearProgressBar_Styles,
            Platform_MaskedEntry_Styles,
            Platform_NavigationView_Styles,
            Platform_NumericInput_Styles,
            Platform_PdfViewer_Styles,
            Platform_Pickers_Styles,
            Platform_PromptInput_Styles,
            Platform_Rating_Styles,
            Platform_RichTextEditor_Styles,
            Platform_Scheduler_Styles,
            Platform_SegmentedControl_Styles,
            Platform_SignaturePad_Styles,
            Platform_Skeleton_Styles,
            Platform_Sliders_Styles,
            Platform_SlideView_Styles,
            Platform_SpeechToTextButton_Styles,
            Platform_TabView_Styles,
            Platform_Toolbar_Styles,
            Platform_TreeDataGrid_Styles,
            Platform_TreeView_Styles,
            Telerik_AIPrompt_Styles,
            Telerik_Accordion_Styles,
            Telerik_AutoComplete_Styles,
            Telerik_BadgeView_Styles,
            Telerik_BottomSheet_Styles,
            Telerik_BusyIndicator_Styles,
            Telerik_Buttons_Styles,
            Telerik_Calendar_Styles,
            Telerik_Chat_Styles,
            Telerik_Chart_Styles,
            Telerik_CheckBox_Styles,
            Telerik_CollectionView_Styles,
            Telerik_ComboBox_Styles,
            Telerik_DataGrid_Styles,
            Telerik_DataForm_Styles,
            Telerik_DataPager_Styles,
            Telerik_Entry_Styles,
            Telerik_Expander_Styles,
            Telerik_GridSplitter_Styles,
            Telerik_ImageEditor_Styles,
            Telerik_LinearProgressBar_Styles,
            Telerik_NavigationView_Styles,
            Telerik_NumericInput_Styles,
            Telerik_PdfViewer_Styles,
            Telerik_Pickers_Styles,
            Telerik_PromptInput_Styles,
            Telerik_Rating_Styles,
            Telerik_RichTextEditor_Styles,
            Telerik_Scheduler_Styles,
            Telerik_SegmentedControl_Styles,
            Telerik_SignaturePad_Styles,
            Telerik_Skeleton_Styles,
            Telerik_Sliders_Styles,
            Telerik_SlideView_Styles,
            Telerik_SpeechToTextButton_Styles,
            Telerik_TabView_Styles,
            Telerik_Toolbar_Styles,
            Telerik_TreeDataGrid_Styles,
            Telerik_TreeView_Styles,
        };

        if (tasks.Count == 0)
        {
            progress?.Invoke(1, 1);    
        }
        else
        {
            progress?.Invoke(0, tasks.Count);
            for(var i = 0; i < tasks.Count; i++)
            {
                await PrefetchResourceDictionaryAsync(tasks[i]);
                progress?.Invoke(i + 1, tasks.Count);
            }
        }
    }

    private static async Task PrefetchResourceDictionaryAsync(Lazy<ResourceDictionary> lazyResoruceDictionary)
    {
        TaskCompletionSource tcs = new TaskCompletionSource();
        Application.Current.Dispatcher.DispatchDelayed(TimeSpan.FromMilliseconds(0), () => {
            Application.Current.Resources.MergedDictionaries.Add(lazyResoruceDictionary.Value);
            Application.Current.Resources.MergedDictionaries.Remove(lazyResoruceDictionary.Value);
            tcs.SetResult();
        });
        await tcs.Task;
    }

    private void MergeThemeResources()
    {
        // Load theme variables and swatches
        switch (this.Theme)
        {
            case TelerikTheme.Default:
                break;
            case TelerikTheme.PlatformLight:
                this.MergedDictionaries.Add(Platform_Swatch_Light.Value);
                this.MergedDictionaries.Add(Platform_Variables.Value);
                break;
            case TelerikTheme.PlatformDark:
                this.MergedDictionaries.Add(Platform_Swatch_Dark.Value);
                this.MergedDictionaries.Add(Platform_Variables.Value);
                break;
            case TelerikTheme.TelerikMain:
                this.MergedDictionaries.Add(Telerik_Swatch_Main.Value);
                this.MergedDictionaries.Add(Telerik_Variables.Value);
                break;
            case TelerikTheme.TelerikMainDark:
                this.MergedDictionaries.Add(Telerik_Swatch_MainDark.Value);
                this.MergedDictionaries.Add(Telerik_Variables.Value);
                break;
            case TelerikTheme.TelerikOceanBlue:
                this.MergedDictionaries.Add(Telerik_Swatch_OceanBlue.Value);
                this.MergedDictionaries.Add(Telerik_Variables.Value);
                break;
            case TelerikTheme.TelerikOceanBlueDark:
                this.MergedDictionaries.Add(Telerik_Swatch_OceanBlueDark.Value);
                this.MergedDictionaries.Add(Telerik_Variables.Value);
                break;
            case TelerikTheme.TelerikPurple:
                this.MergedDictionaries.Add(Telerik_Swatch_Purple.Value);
                this.MergedDictionaries.Add(Telerik_Variables.Value);
                break;
            case TelerikTheme.TelerikPurpleDark:
                this.MergedDictionaries.Add(Telerik_Swatch_PurpleDark.Value);
                this.MergedDictionaries.Add(Telerik_Variables.Value);
                break;
            case TelerikTheme.TelerikTurquoise:
                this.MergedDictionaries.Add(Telerik_Swatch_Turquoise.Value);
                this.MergedDictionaries.Add(Telerik_Variables.Value);
                break;
            case TelerikTheme.TelerikTurquoiseDark:
                this.MergedDictionaries.Add(Telerik_Swatch_TurquoiseDark.Value);
                this.MergedDictionaries.Add(Telerik_Variables.Value);
                break;
            default:
                throw new Exception($"Theme not available, key: {this.Theme}");
        }

        // Load control styles
        if (this.Theme.ToString().StartsWith("Platform"))
        {
            this.MergedDictionaries.Add(Platform_AIPrompt_Styles.Value);
            this.MergedDictionaries.Add(Platform_Accordion_Styles.Value);
            this.MergedDictionaries.Add(Platform_AutoComplete_Styles.Value);
            this.MergedDictionaries.Add(Platform_BadgeView_Styles.Value);
            this.MergedDictionaries.Add(Platform_BottomSheet_Styles.Value);
            this.MergedDictionaries.Add(Platform_BusyIndicator_Styles.Value);
            this.MergedDictionaries.Add(Platform_Buttons_Styles.Value);
            this.MergedDictionaries.Add(Platform_Calendar_Styles.Value);
            this.MergedDictionaries.Add(Platform_Chat_Styles.Value);
            this.MergedDictionaries.Add(Platform_CheckBox_Styles.Value);
            this.MergedDictionaries.Add(Platform_CollectionView_Styles.Value);
            this.MergedDictionaries.Add(Platform_ComboBox_Styles.Value);
            this.MergedDictionaries.Add(Platform_DataGrid_Styles.Value);
            this.MergedDictionaries.Add(Platform_DataForm_Styles.Value);
            this.MergedDictionaries.Add(Platform_DataPager_Styles.Value);
            this.MergedDictionaries.Add(Platform_Entry_Styles.Value);
            this.MergedDictionaries.Add(Platform_Expander_Styles.Value);
            this.MergedDictionaries.Add(Platform_GridSplitter_Styles.Value);
            this.MergedDictionaries.Add(Platform_ImageEditor_Styles.Value);
            this.MergedDictionaries.Add(Platform_LinearProgressBar_Styles.Value);
            this.MergedDictionaries.Add(Platform_MaskedEntry_Styles.Value);
            this.MergedDictionaries.Add(Platform_NavigationView_Styles.Value);
            this.MergedDictionaries.Add(Platform_NumericInput_Styles.Value);
            this.MergedDictionaries.Add(Platform_PdfViewer_Styles.Value);
            this.MergedDictionaries.Add(Platform_Pickers_Styles.Value);
            this.MergedDictionaries.Add(Platform_PromptInput_Styles.Value);
            this.MergedDictionaries.Add(Platform_Rating_Styles.Value);
            this.MergedDictionaries.Add(Platform_RichTextEditor_Styles.Value);
            this.MergedDictionaries.Add(Platform_Scheduler_Styles.Value);
            this.MergedDictionaries.Add(Platform_SegmentedControl_Styles.Value);
            this.MergedDictionaries.Add(Platform_SignaturePad_Styles.Value);
            this.MergedDictionaries.Add(Platform_Skeleton_Styles.Value);
            this.MergedDictionaries.Add(Platform_Sliders_Styles.Value);
            this.MergedDictionaries.Add(Platform_SlideView_Styles.Value);
            this.MergedDictionaries.Add(Platform_SpeechToTextButton_Styles.Value);
            this.MergedDictionaries.Add(Platform_TabView_Styles.Value);
            this.MergedDictionaries.Add(Platform_Toolbar_Styles.Value);
            this.MergedDictionaries.Add(Platform_TreeDataGrid_Styles.Value);
            this.MergedDictionaries.Add(Platform_TreeView_Styles.Value); 
        }
        else if (this.Theme.ToString().StartsWith("Telerik"))
        {
            this.MergedDictionaries.Add(Telerik_AIPrompt_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Accordion_Styles.Value);
            this.MergedDictionaries.Add(Telerik_AutoComplete_Styles.Value);
            this.MergedDictionaries.Add(Telerik_BadgeView_Styles.Value);
            this.MergedDictionaries.Add(Telerik_BottomSheet_Styles.Value);
            this.MergedDictionaries.Add(Telerik_BusyIndicator_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Buttons_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Calendar_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Chat_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Chart_Styles.Value);
            this.MergedDictionaries.Add(Telerik_CheckBox_Styles.Value);
            this.MergedDictionaries.Add(Telerik_CollectionView_Styles.Value);
            this.MergedDictionaries.Add(Telerik_ComboBox_Styles.Value);
            this.MergedDictionaries.Add(Telerik_DataGrid_Styles.Value);
            this.MergedDictionaries.Add(Telerik_DataForm_Styles.Value);
            this.MergedDictionaries.Add(Telerik_DataPager_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Entry_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Expander_Styles.Value);
            this.MergedDictionaries.Add(Telerik_GridSplitter_Styles.Value);
            this.MergedDictionaries.Add(Telerik_ImageEditor_Styles.Value);
            this.MergedDictionaries.Add(Telerik_LinearProgressBar_Styles.Value);
            this.MergedDictionaries.Add(Telerik_NavigationView_Styles.Value);
            this.MergedDictionaries.Add(Telerik_NumericInput_Styles.Value);
            this.MergedDictionaries.Add(Telerik_PdfViewer_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Pickers_Styles.Value);
            this.MergedDictionaries.Add(Telerik_PromptInput_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Rating_Styles.Value);
            this.MergedDictionaries.Add(Telerik_RichTextEditor_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Scheduler_Styles.Value);
            this.MergedDictionaries.Add(Telerik_SegmentedControl_Styles.Value);
            this.MergedDictionaries.Add(Telerik_SignaturePad_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Skeleton_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Sliders_Styles.Value);
            this.MergedDictionaries.Add(Telerik_SlideView_Styles.Value);
            this.MergedDictionaries.Add(Telerik_SpeechToTextButton_Styles.Value);
            this.MergedDictionaries.Add(Telerik_TabView_Styles.Value);
            this.MergedDictionaries.Add(Telerik_Toolbar_Styles.Value);
            this.MergedDictionaries.Add(Telerik_TreeDataGrid_Styles.Value);
            this.MergedDictionaries.Add(Telerik_TreeView_Styles.Value);
        }
    }
}

public enum TelerikTheme
{
    Default,
    PlatformLight,
    PlatformDark,
    TelerikMain,
    TelerikMainDark,
    TelerikOceanBlue,
    TelerikOceanBlueDark,
    TelerikPurple,
    TelerikPurpleDark,
    TelerikTurquoise,
    TelerikTurquoiseDark,
}
